version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sparkles-autobrr_web_1
      APP_PORT: 7474
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/autobrr/autobrr:v1.28.0@sha256:529f44efc8601bad020655c1d9fe45f1400c05ebfad7cfbb1fbb9a708fd8cbfe
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/config:/config
    environment:
      AUTOBRR__PORT: 7474
      AUTOBRR__HOST: "0.0.0.0"
